/**
 * ============================================
 * App Entry Point — Amplify Configuration
 * ============================================
 *
 * This is where the React app starts and where
 * AWS Amplify is initialized.
 *
 * Amplify.configure(outputs) tells the Amplify SDK:
 *   - Where the Cognito User Pool is (region, pool ID)
 *   - Where the AppSync API is (endpoint URL)
 *   - What authentication mode to use
 *
 * The `amplify_outputs.json` file is AUTO-GENERATED by
 * Amplify during deployment — you never write it manually.
 *
 * File: src/main.jsx
 */

import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { Amplify } from 'aws-amplify'

/**
 * amplify_outputs.json — Auto-generated connection config.
 *
 * Contains:
 *   {
 *     "auth": {
 *       "user_pool_id": "us-east-1_xxxxx",
 *       "user_pool_client_id": "xxxxx",
 *       "identity_pool_id": "us-east-1:xxxxx"
 *     },
 *     "data": {
 *       "url": "https://xxxxx.appsync-api.us-east-1.amazonaws.com/graphql",
 *       "default_authorization_type": "AMAZON_COGNITO_USER_POOLS"
 *     }
 *   }
 *
 * This file is generated when:
 *   - Running `npx ampx sandbox` (local dev)
 *   - Amplify Console builds your app (production)
 */
import outputs from '../amplify_outputs.json'

import './index.css'
import App from './App.jsx'

/**
 * Amplify.configure() — Initializes the AWS SDK.
 *
 * After this call, all Amplify features are ready:
 *   - Authentication (signIn, signUp, signOut)
 *   - Data operations (create, read, update, delete)
 *   - The <Authenticator> component knows which User Pool to use
 *   - The generateClient() knows which AppSync endpoint to call
 *
 * This MUST be called before any Amplify components render.
 */
Amplify.configure(outputs)

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
